# Generated by Django 2.0 on 2019-02-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
