# Generated by Django 2.0 on 2019-02-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0005_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
